version: '3.8'
services:
  app:
    build: .
    volumes:
      - todolist-db:/app/data
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/config/docker-server.yml"

volumes:
  todolist-db:
