version: '3'

tasks:
  server:
    cmds:
      - JWT_SECRET=12345678 go run ./cmd/server/main.go --config=./config/server.yml
  migrate:
    cmds:
      - go run ./cmd/migrate/main.go --config=./config/server.yml
  test-migrate:
    cmds:
      - go run ./cmd/migrate/main.go --config=./config/test-server.yml
