name: "test-todolist"
protocol: "rest"
port: 8001
timeout: "10s"
env: "test"
version: "v0.0.1"
domain: "localhost"
database:
  test: true
  path: "./database/test.db"
jwt:
  enabled: true
  duration: "1h"